### ISSUE TITLE
Outdated links to JMdict-based dictionaries

### ISSUE THREAD

**Issue by stephenmk** [donkuri/learn-japanese#2]
In your guide, some of the download links to dictionaries based on JMdict/JMnedict/Kanjidic materials are outdated. I was wondering if you would consider updating them to point toward dynamic pages that are regularly updated.

Dictionary | Current link | Regularly Updated Link
-- | -- | --
"JMdict Extra" | https://github.com/Aquafina-water-bottle/jmdict-english-yomichan/releases/latest/download/2023-06-19_jmdict_english_extra_with_examples.zip | https://github.com/themoeway/jmdict-yomitan/releases/latest
Jitendex | https://github.com/stephenmk/Jitendex/releases/download/v3.0-3/jitendex-yomichan-2023-11-29.zip | https://github.com/stephenmk/Jitendex/releases/latest
Kanjidic | https://drive.google.com/file/d/1uE6vO1n6v7ENzfYDWFS3Kx7EnttecqeF/view?usp=drive_link | https://github.com/themoeway/jmdict-yomitan/releases/latest

I guess a lot of people aren't aware of this (Aquafina-water-bottle didn't mention it anywhere in his repo), but the so-called "JMdict Extra" and new JMnedict dictionary versions for Yomichan were entirely designed and developed by me.[^1][^2][^3][^4][^5] Jitendex is a continuation of that project which I started to support more app formats than just Yomichan, to move the codebase from golang to python, and to continue adding more features and design improvements. So statements like this are a little perplexing to me:

> **JMdict (extra with examples) or Jitendex**
> Both are good, Jitendex is a more recent version but some people prefer JMdict. Download both, try both and see which one you prefer.

Of course I'm biased, but I wonder if your readers might also want to know why "some people" prefer the old version. Is it because those people already configured their flashcards to work with the older version and don't want to reconfigure it for Jitendex? That's a perfectly valid reason, but it doesn't really affect new users. Or is it some other reason? I'm open to constructive feedback.

[^1]: https://github.com/FooSoft/yomichan/issues/2111
[^2]: https://github.com/FooSoft/yomichan/issues/2183
[^3]: https://github.com/FooSoft/yomichan-import/pull/40
[^4]: https://github.com/FooSoft/yomichan-import/pull/41
[^5]: https://github.com/FooSoft/yomichan/issues/1165

**Comment by donkuri** [comment]
Thank you very much for commenting on this, I was taken with exams and didn't have the time to update the website. I will do so tomorrow. Thank you especially for providing the correct links to update the website.

> Of course I'm biased, but I wonder if your readers might also want to know why "some people" prefer the old version. Is it because those people already configured their flashcards to work with the older version and don't want to reconfigure it for Jitendex? That's a perfectly valid reason, but it doesn't really affect new users. Or is it some other reason? I'm open to constructive feedback.

There have been a few people that have mentioned this to me. They have mostly focused on the design of the dictionary while using Yomichan/Yomitan, preferring the older version. I assume this can be fixed with just a little bit of CSS, but I do not expect most people to play around with the visual look of their Yomichan pop-up windows, nor with the flashcards in Anki. I agree I haven't been especially clear on that statement, so I will update it to explain what exactly made some people prefer the older version. I will also explain what Jitendex exactly is with respect to JMdict, "more recent version" is ambiguous at best, plain wrong at worst.

**Comment by stephenmk** [comment]
Sounds good to me. Thanks for your time.
